name: Storybook Build
on:
  push:
    branches:
      - main # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn install
          yarn run build-storybook
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: show
          build_dir: storybook-static
          commit_message: 'chore(deploy): Storybook'
          keep_history: false
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.DELOY_STORYBOOK }}
